### ISSUE TITLE
All WISE

### ISSUE THREAD

**Issue by krislars** [krislars/AA_Tau_Covey#4]
maybe neowise

look for 3-4 micron data

Look at how it extrapolates into the MIR

Try spitzer?

**Comment by kevincovey** [comment]
* Spitzer spectra -- looks like there are 8 spectra from 5 to 15 microns taken between 2005 and 2007, and 2 spectra covering 10-37 microns taken in 2005.  Should be a good dataset for linking with the 2008 optical/NIR data.

See data & download FITS files (or VOTables?) from [http://cassis.sirtf.com/atlas/cgi/radec.py?ra=68.73093&dec=24.481433&radius=20](http://cassis.sirtf.com/atlas/cgi/radec.py?ra=68.73093&dec=24.481433&radius=20)

* I've also figured out how to query the NEOWISE database for all the detections of a given source, and it looks like AA Tau has been detected ~84 times in W1 (3.4 microns) and W2 (4.6 microns) since WISE was re-activated in 2013.  

The file of all those detections is attached [AATau_NEOWISE.tbl.zip](https://github.com/krislars/AA_Tau_Covey/files/1289425/AATau_NEOWISE.tbl.zip), and while W2 isn't quite overlapping with the Spitzer spectra above, hopefully it is close enough to estimate something about the variations between 2008 and 2014?  

Each NEOWISE detection also lists the original cryogenic detection from ~2010 (before the deep dimming event), so it should be possible to do a pre/post fade comparison strictly from WISE data, I think.  Note that the NEOWISE data seems to indicate ~0.5 mag variability during the 2014-2017 period, though, which is more than I would have expected -- maybe this is the source getting brighter as it emerges from the fade?  But still, if extinction was behind most of the variations, explaining a half a mag of variation at 3-5 microns probably requires a ridiculous amount of dust, so maybe we're seeing some other thermal change in the system, and this data will just make things more complicated?

**Comment by krislars** [comment]
Next paper!!
